version: '3.8'
services:
  app:
    container_name: next-app
    build:
      context: .
    tty: true
    environment:
    - WATCHPACK_POLLING=true
    volumes:
    - ./next-app:/app
    ports:
    - '3000:3000'
    - '5555:5555'
    restart: always
    networks:
      - app_network
    command: sh -c "npm run dev"
    depends_on:
      - db
  e2e:
    container_name: playwright
    tty: true
    build:
      context: ./e2e
      dockerfile: ./Dockerfile.e2e
    environment:
      - DISPLAY=:0
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./e2e/playwright:/e2e
    ports:
      - "9333:9333"
    ipc: host
    networks:
      - app_network
  db:
    image: postgres:16-alpine
    container_name: "${CONTAINER_NAME}"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: app_db
    ports:
      - 5432:5432
    restart: always
    volumes:
      - ./postgres/db:/var/lib/postgresql/data/
    networks:
      - app_network

networks:
  app_network:
    driver: bridge