import type { Metadata } from "next";
import { Zen_Antique } from "next/font/google";
import "./globals.css";

const zen = Zen_Antique({
  weight: '400',
  display: 'swap',
  preload: false,
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "fullstack-nextjs-nextauth-postgres-app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={zen.className}>{children}</body>
    </html>
  );
}
